Get user by id
danielDAWRA/ByteBazaarAPI pull request #6
Opened 2024-01-15 18:40 UTC by jaanmeld

2024-01-15 19:02 UTC, Ahuanmarca requested changes
Please add your route to router.js in the /api directory.

2024-01-15 19:02 UTC, Ahuanmarca commented on src/api/users/users.model.js
> +  },
I think we should have 'unique' restriction in the email field. What do you think?

2024-01-15 19:04 UTC, andreamir requested changes

2024-01-15 19:04 UTC, andreamir commented on src/api/users/users.router.js
> +router.get('/id/:id', usersController.getById);
In the **gameTitle.getById** route, the current implementation is:

`router.get('/:id', gameTitlesController.getById);`

We should aim to maintain a consistent approach for all routes.

2024-01-15 19:32 UTC, nuinn approved these changes

2024-01-15 19:40 UTC, andreamir requested changes
You have conflicts to resolve before merging into the 'develop' branch.

2024-01-15 19:44 UTC, Ahuanmarca approved these changes

2024-01-17 17:28 UTC, andreamir requested changes
You have conflicts to resolve before merging into the 'develop' branch.

2024-01-17 17:46 UTC, andreamir approved these changes

2024-01-17 17:49 UTC, JonaTheBridge approved these changes

2024-01-17 17:49 UTC, merged