[Route] Get Genre By Id
danielDAWRA/ByteBazaarAPI pull request #7
Opened 2024-01-15 19:31 UTC by Ahuanmarca

2024-01-15 19:40 UTC, nuinn commented on src/api/genres/genres.router.js
> +router.get('/byId/:id', genresController.getGenreById);
The uniform byId router for the project has been '/:id/' without '/byId/', '/id/', etc. Would you like to keep this router?

2024-01-15 19:44 UTC, andreamir commented on .gitignore
> +.prettierrc
For those who do not have Prettier installed, this line is not necessary.
However, it doesn't hurt since it can prevent conflicts. 🥰

2024-01-17 10:36 UTC, jaanmeld approved these changes

2024-01-17 11:18 UTC, nuinn requested changes
In terms of functionality, it's great. But I don't know if you want to change the router path to match the others in the project before we merge it?

2024-01-17 17:34 UTC, andreamir reviewed
awaiting the route byId/:id to be changed

2024-01-17 17:47 UTC, nuinn approved these changes

2024-01-17 17:51 UTC, andreamir approved these changes

2024-01-17 18:06 UTC, JonaTheBridge requested changes

2024-01-17 18:06 UTC, JonaTheBridge commented on src/api/router.js
> +// router.use('/auth', authRouter);
Todas estas lineas comentadas, si se comentan porque dan error, prefiero que las elimines y que las cree el que las necesite.

2024-01-17 18:22 UTC, JonaTheBridge approved these changes

2024-01-17 18:22 UTC, merged